# Generated by Django 5.1.4 on 2025-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_address_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                default="mimra", max_length=255, verbose_name="Улица"
            ),
            preserve_default=False,
        ),
    ]
