# Generated by Django 5.1.4 on 2025-07-22 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="address",
            name="company",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название компании"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="firstname",
            field=models.CharField(
                default="hiu",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Имя может содержать только буквы",
                        regex="^[A-Za-zА-Яа-яЁё\\-]+$",
                    )
                ],
                verbose_name="Имя",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="lastname",
            field=models.CharField(
                default="weobok",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Фамилия может содержать только буквы",
                        regex="^[A-Za-zА-Яа-яЁё\\-]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addresses",
                to="users.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="users.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regions",
                to="users.country",
                verbose_name="Страна",
            ),
        ),
    ]
