# Generated by Django 5.1.4 on 2025-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_payment_method_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Выполнен"),
                    ("in_shop", "В магазине"),
                    ("in_transit", "В пути"),
                    ("processing", "Обработка"),
                    ("cancelled", "Отменен"),
                    ("pending_payment", "Не оплачен"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
