# Generated by Django 5.1.4 on 2025-07-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_shopaddress"),
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopaddress",
            options={
                "verbose_name": "Адрес магазина",
                "verbose_name_plural": "Адреса магазинов",
            },
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="business_hours",
            field=models.JSONField(default=dict, verbose_name="Рабочие часы"),
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops_addresses",
                to="users.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Долгота"
            ),
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="shopaddress",
            name="street",
            field=models.CharField(max_length=200, verbose_name="Адрес"),
        ),
    ]
