# Generated by Django 5.1.4 on 2025-07-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_status_alter_order_delivery_method"),
        ("product", "0012_shopaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="product.shopaddress",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="product.product",
            ),
        ),
    ]
