# Generated by Django 5.1.4 on 2025-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_shop_address_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Оплата картой на сайте"),
                    ("in_store", "Оплата в магазине"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Выполнен"),
                    ("in_transit", "В пути"),
                    ("processing", "Обработка"),
                    ("cancelled", "Отменен"),
                    ("pending_payment", "Не оплачен"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
