# Generated by Django 5.1.4 on 2025-07-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_shopaddress_options_and_more"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to="product.product",
            ),
        ),
    ]
