# Generated by Django 5.1.4 on 2025-07-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_cart_session_key_alter_cart_user"),
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("business_hours", models.JSONField(default=dict)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.city"
                    ),
                ),
            ],
        ),
    ]
